# Generated by Django 4.0.5 on 2022-07-03 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='short',
            field=models.CharField(default='sci', max_length=3),
        ),
    ]
