# Generated by Django 4.0.5 on 2022-07-24 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourapp', '0005_post_registereduser_reply_registereduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reply',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
