# Generated by Django 4.0.5 on 2022-07-24 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourapp', '0006_post_edited_reply_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='replycounter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='viewcounter',
            field=models.IntegerField(default=0),
        ),
    ]
