# Generated by Django 4.0.5 on 2022-07-24 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fourapp', '0007_post_replycounter_post_viewcounter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='replycounter',
        ),
    ]
