# Generated by Django 4.0.5 on 2022-08-16 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourapp', '0009_category_nsfw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='short',
            field=models.CharField(default='aaa', max_length=3, unique=True),
        ),
    ]
