# Generated by Django 4.0.5 on 2022-08-29 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourusers', '0003_remove_userprofile_id_remove_userprofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
